APT::FTPArchive::Release::Origin "Ishimura";
APT::FTPArchive::Release::Label "Ishimura Service Pack Repository for Tridentu 2";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64";
APT::FTPArchive::Release::Components "core-kernel core-userspace core-userspace-env core-userspace-backup-gui core-userspace-plasma-gui core-userspace-base alt-kernel";


Dir {
  BaseDir ".";
  CacheDir ".";
};

Default {
  Packages::Compress ". xz";
};

Tree "./dists/stable" {
  Sections "core-kernel core-userspace core-userspace-env core-userspace-backup-gui core-userspace-plasma-gui core-userspace-base alt-kernel";
  Architectures "amd64";
};

# ====== Section to Physical Folder Layout Overrides ======

BinDirectory "./dists/stable/core-kernel/binary-amd64" {
  Packages "dists/stable/core-kernel/binary-amd64/Packages";
};

BinDirectory "./dists/stable/alt-kernel/binary-amd64" {
  Packages "dists/stable/alt-kernel/binary-amd64/Packages";
};

BinDirectory "./dists/stable/core-userspace/binary-amd64" {
  Packages "dists/stable/core-userspace/binary-amd64/Packages";
};

BinDirectory "./dists/stable/core-userspace-env/binary-amd64" {
  Packages "dists/stable/core-userspace-env/binary-amd64/Packages";
};

BinDirectory "./dists/stable/core-userspace-backup-gui/binary-amd64" {
  Packages "dists/stable/core-userspace-backup-gui/binary-amd64/Packages";
};

BinDirectory "./dists/stable/core-userspace-plasma-gui/binary-amd64" {
  Packages "dists/stable/core-userspace-plasma-gui/binary-amd64/Packages";
};

BinDirectory "./dists/stable/core-userspace-base/binary-amd64" {
  Packages "dists/stable/core-userspace-base/binary-amd64/Packages";
};
