Dir {
  BaseDir ".";
  CacheDir ".";
};

Default {
  Packages::Compress ". gzip";
};

Tree "dists/stable" {
  Sections "core-kernel core-userspace core-userspace-env core-userspace-backup-gui core-userspace-plasma-gui core-userspace-base";
  Architectures "amd64";
};
