APT::FTPArchive::Release::Origin "Ishimura";
APT::FTPArchive::Release::Label "Ishimura Service Pack Repository for Tridentu 2";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64";
APT::FTPArchive::Release::Components "core-kernel core-userspace core-userspace-env core-userspace-backup-gui core-userspace-plasma-gui core-userspace-base alt-kernel";

Dir {
  ArchiveDir ".";  # Set this to repo root
  CacheDir ".";
};

Default {
  Packages::Compress ". xz";
};

# The Tree block automatically matches dists/stable/ sections
# to your pool/ folder structure automatically.
Tree "dists/stable" {
  Sections "core-kernel core-userspace core-userspace-env core-userspace-backup-gui core-userspace-plasma-gui core-userspace-base alt-kernel";
  Architectures "amd64";
  Directory "pool"; # Tells apt-ftparchive that files sit inside pool/
};
